### ISSUE TITLE
RpcServer doesn't compile

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#424]
Note, the compile issues in StateService are tracked by #415.  RpcServer compile was broken by #409 

```
C:\Users\harry\Source\neo\official\modules\src\StateService\MPT\MPTNodeType.cs(7,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
C:\Users\harry\Source\neo\official\modules\src\StateService\MPT\MPTNodeType.cs(9,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
C:\Users\harry\Source\neo\official\modules\src\StateService\MPT\MPTNodeType.cs(11,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
C:\Users\harry\Source\neo\official\modules\src\StateService\MPT\MPTNodeType.cs(13,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
C:\Users\harry\Source\neo\official\modules\src\RpcServer\RpcServer.SmartContract.cs(113,37): error CS1061: 'SnapshotView' does not contain a definition for 'Contracts' and no accessible extension method 'Contracts' accepting a first argument of type 'SnapshotView' could be found (are you missing a using directive or an assembly reference?) [C:\Users\harry\Source\neo\official\modules\src\RpcServer\RpcServer.csproj]
```

**Comment by superboyiii** [comment]
> Note, the compile issues in StateService are tracked by #415. RpcServer compile was broken by #409
> 
> ```
> C:\Users\harry\Source\neo\official\modules\src\StateService\MPT\MPTNodeType.cs(7,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
> C:\Users\harry\Source\neo\official\modules\src\StateService\MPT\MPTNodeType.cs(9,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
> C:\Users\harry\Source\neo\official\modules\src\StateService\MPT\MPTNodeType.cs(11,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
> C:\Users\harry\Source\neo\official\modules\src\StateService\MPT\MPTNodeType.cs(13,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
> C:\Users\harry\Source\neo\official\modules\src\RpcServer\RpcServer.SmartContract.cs(113,37): error CS1061: 'SnapshotView' does not contain a definition for 'Contracts' and no accessible extension method 'Contracts' accepting a first argument of type 'SnapshotView' could be found (are you missing a using directive or an assembly reference?) [C:\Users\harry\Source\neo\official\modules\src\RpcServer\RpcServer.csproj]
> ```

RpcServer compile was fixed in https://github.com/neo-project/neo-modules/pull/420, but the compile issues in StateService is waiting for https://github.com/neo-project/neo-modules/pull/414, not sure if it could be merged before Preview4, but since it's not implement any fucuntions on neo-cli, I'll not release it in Preview4 plugins.

**Comment by devhawk** [comment]
>  since it doesn't implement any fucuntions on neo-cli, I'll not release it in Preview4 plugins.

Makes sense. Preview 4 is the priority right now

**Comment by gsmachado** [comment]
I'm executing this command in my docker image:

```
dotnet restore && dotnet publish -r linux-x64 -c Release -o /plugins
```

@devhawk Is there any way to "exclude" certain projects from the restore?

**Comment by devhawk** [comment]
AFAIK, no - Not without changing the .sln or csproj files in some way (example: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-exclude-projects-from-a-build?view=vs-2019)

**Comment by superboyiii** [comment]
> @superboyiii might be worth removing StateService from neo-modules.sln until it's compiling

@devhawk @gsmachado I'll remove StateService on Preview4 branch.
